[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# Cronos Testnet
[rpc_endpoints]
cronos-testnet = "https://evm-t3.cronos.org"
cronos = "https://evm.cronos.org"

[etherscan]
cronos-testnet = { key = "${CRONOSCAN_API_KEY}", url = "https://api-testnet.cronoscan.com/api" }
cronos = { key = "${CRONOSCAN_API_KEY}", url = "https://api.cronoscan.com/api" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
